branches:
  only:
    - master
language: php
php:
  - 5.4
  - 5.3
  - 5.5
before_script:
  - echo "extension=mongo.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - echo "date.timezone=Europe/Moscow" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - composer install --dev
script: "cd tests && phpunit --exclude-group=mongo"
